# Site settings
title: Honno's Blorg
email: quitesimplymatt@gmail.com
description: >-
  Personal blog of Matthew Barber.
baseurl: "/"
url: "https://blog.matthewbarber.io/"
master_url: "https://matthewbarber.io/"
twitter_username: WhoStoleHonno
github_username: Honno

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
